/**
 * iOS Device Specifications for PWA Startup Images
 *
 * Each device requires apple-touch-startup-image link elements with
 * media queries targeting specific viewport sizes and pixel ratios.
 *
 * The images are dynamically generated by the backend at:
 * /api/startup-image/{width}/{height}?orientation={portrait|landscape}
 *
 * @module lib/ios-startup-images
 */

/**
 * iOS device startup image specification
 */
interface IOSStartupImage {
  /** CSS viewport width */
  width: number;
  /** CSS viewport height */
  height: number;
  /** Device pixel ratio */
  ratio: number;
  /** Actual image width (width × ratio) */
  imgW: number;
  /** Actual image height (height × ratio) */
  imgH: number;
}

/**
 * All supported iOS devices for startup images.
 * Deduplicated by unique viewport + pixel ratio combinations.
 */
export const IOS_STARTUP_IMAGES: IOSStartupImage[] = [
  // iPhone 16 Pro Max (2024)
  { width: 440, height: 956, ratio: 3, imgW: 1320, imgH: 2868 },
  // iPhone 16 Pro (2024)
  { width: 402, height: 874, ratio: 3, imgW: 1206, imgH: 2622 },
  // iPhone 16 Plus (2024)
  { width: 430, height: 932, ratio: 3, imgW: 1290, imgH: 2796 },
  // iPhone 16 (2024)
  { width: 393, height: 852, ratio: 3, imgW: 1179, imgH: 2556 },
  // iPhone 14 Plus / 13 Pro Max / 12 Pro Max
  { width: 428, height: 926, ratio: 3, imgW: 1284, imgH: 2778 },
  // iPhone 14 / 13 / 13 Pro / 12 / 12 Pro
  { width: 390, height: 844, ratio: 3, imgW: 1170, imgH: 2532 },
  // iPhone 13 mini / 12 mini / 11 Pro / X / XS
  { width: 375, height: 812, ratio: 3, imgW: 1125, imgH: 2436 },
  // iPhone 11 Pro Max / XS Max
  { width: 414, height: 896, ratio: 3, imgW: 1242, imgH: 2688 },
  // iPhone 11 / XR
  { width: 414, height: 896, ratio: 2, imgW: 828, imgH: 1792 },
  // iPhone SE (3rd/2nd gen) / 8 / 7 / 6s
  { width: 375, height: 667, ratio: 2, imgW: 750, imgH: 1334 },
  // iPhone 8 Plus / 7 Plus / 6s Plus
  { width: 414, height: 736, ratio: 3, imgW: 1242, imgH: 2208 },
  // iPhone SE (1st gen) / 5s
  { width: 320, height: 568, ratio: 2, imgW: 640, imgH: 1136 },

  // iPads
  // iPad Pro 13" (M4)
  { width: 1032, height: 1376, ratio: 2, imgW: 2064, imgH: 2752 },
  // iPad Pro 11" (M4)
  { width: 834, height: 1210, ratio: 2, imgW: 1668, imgH: 2420 },
  // iPad Air 13" / iPad Pro 12.9" (older)
  { width: 1024, height: 1366, ratio: 2, imgW: 2048, imgH: 2732 },
  // iPad Air 11" / iPad 10th
  { width: 820, height: 1180, ratio: 2, imgW: 1640, imgH: 2360 },
  // iPad mini 7th/6th
  { width: 744, height: 1133, ratio: 2, imgW: 1488, imgH: 2266 },
  // iPad Pro 11" (older)
  { width: 834, height: 1194, ratio: 2, imgW: 1668, imgH: 2388 },
  // iPad Pro 10.5" / iPad Air 3rd
  { width: 834, height: 1112, ratio: 2, imgW: 1668, imgH: 2224 },
  // iPad 9th/8th/7th
  { width: 810, height: 1080, ratio: 2, imgW: 1620, imgH: 2160 },
  // iPad 6th/5th / Air 2 / Pro 9.7" / mini 5th/4th
  { width: 768, height: 1024, ratio: 2, imgW: 1536, imgH: 2048 },
];

/**
 * Generate iOS startup image link elements as a string.
 * For use in dangerouslySetInnerHTML.
 *
 * Each device gets two link elements:
 * - Portrait orientation
 * - Landscape orientation (with swapped dimensions)
 *
 * @returns HTML string of link elements
 */
export function generateIOSStartupImageLinks(): string {
  const links: string[] = [];

  for (const device of IOS_STARTUP_IMAGES) {
    // Portrait orientation
    links.push(
      `<link rel="apple-touch-startup-image" ` +
        `href="/api/startup-image/${device.imgW}/${device.imgH}" ` +
        `media="(device-width: ${device.width}px) and (device-height: ${device.height}px) and (-webkit-device-pixel-ratio: ${device.ratio}) and (orientation: portrait)">`
    );

    // Landscape orientation (swap width/height for image)
    links.push(
      `<link rel="apple-touch-startup-image" ` +
        `href="/api/startup-image/${device.imgH}/${device.imgW}" ` +
        `media="(device-width: ${device.width}px) and (device-height: ${device.height}px) and (-webkit-device-pixel-ratio: ${device.ratio}) and (orientation: landscape)">`
    );
  }

  return links.join("\n");
}
